config/routes.rb
Rails.application.routes.draw do
  resources :course_instructors
  resources :program_sessions
  resources :answers
  resources :choices
  resources :questions
  resources :papers
  resources :programs
  resources :sessions
  resources :instructors
  resources :exams
  resources :courses
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "welcome#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :course
  belongs_to :instructor
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_instructors
	has_many :instructors, through: :course_instructors
	
  validates :title, presence: true
	validates :code, presence: true


end

app/models/course_instructor.rb
class CourseInstructor < ApplicationRecord

  belongs_to :course
  belongs_to :instructor

  has_many :papers

  def course_with_instructor
    "#{Course.find(course_id).title} - #{Instructor.find(instructor_id).name}"
  end

end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :papers
end

app/models/instructor.rb
class Instructor < ApplicationRecord

	has_many :courses, through: :course_instructors
	has_many :course_instructors

end

app/models/paper.rb
class Paper < ApplicationRecord

  belongs_to :program_session, foreign_key: 'program_sessions_id'
  belongs_to :course_instructor, foreign_key: 'course_instructors_id'
  belongs_to :exam

  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/program.rb
class Program < ApplicationRecord

	has_many :sessions, through: :program_sessions

  def name_with_nature
    "#{name} - #{nature}"
  end
end

app/models/program_session.rb
class ProgramSession < ApplicationRecord

  belongs_to :program
  belongs_to :session

  has_many :papers

  def program_with_session
    "#{Program.find(program_id).name_with_nature} - #{Session.find(session_id).session_start_finish}"
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :paper
	has_many :choices, dependent: :destroy
	has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
end

app/models/session.rb
class Session < ApplicationRecord

  has_many :programs, through: :program_sessions

  def session_start_finish
    "#{start.strftime("%Y")} - #{finish.strftime("%Y")}"
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:description, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/choices/_form.html.erb
<%= form_with(model: choice, local: true) do |form| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.description %></td>
        <td><%= choice.question %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @choice.description %>
</p>

<p>
  <strong>Question:</strong>
  <%= @choice.question %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>