config/routes.rb
Rails.application.routes.draw do
  resources :course_instructors
  resources :program_sessions
  resources :answers
  resources :choices
  resources :questions
  resources :papers
  resources :programs
  resources :sessions
  resources :instructors
  resources :exams
  resources :courses
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "welcome#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :choice
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :course
  belongs_to :instructor
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_instructors
	has_many :instructors, through: :course_instructors
	
  validates :title, presence: true
	validates :code, presence: true


end

app/models/course_instructor.rb
class CourseInstructor < ApplicationRecord

  belongs_to :course
  belongs_to :instructor

  has_many :papers

  def course_with_instructor
    "#{Course.find(course_id).title} - #{Instructor.find(instructor_id).name}"
  end

end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :papers
end

app/models/instructor.rb
class Instructor < ApplicationRecord

	has_many :courses, through: :course_instructors
	has_many :course_instructors

end

app/models/paper.rb
class Paper < ApplicationRecord

  belongs_to :program_session, foreign_key: 'program_sessions_id'
  belongs_to :course_instructor, foreign_key: 'course_instructors_id'
  belongs_to :exam

  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/program.rb
class Program < ApplicationRecord

	has_many :sessions, through: :program_sessions

  def name_with_nature
    "#{name} - #{nature}"
  end
end

app/models/program_session.rb
class ProgramSession < ApplicationRecord

  belongs_to :program
  belongs_to :session

  has_many :papers

  def program_with_session
    "#{Program.find(program_id).name_with_nature} - #{Session.find(session_id).session_start_finish}"
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :paper
	has_many :choices, dependent: :destroy
	has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
end

app/models/session.rb
class Session < ApplicationRecord

  has_many :programs, through: :program_sessions

  def session_start_finish
    "#{start.strftime("%Y")} - #{finish.strftime("%Y")}"
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :email)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.name %></td>
        <td><%= instructor.email %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.email %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>