config/routes.rb
Rails.application.routes.draw do
  resources :course_instructors
  resources :program_sessions
  resources :answers
  resources :choices
  resources :questions
  resources :papers
  resources :programs
  resources :sessions
  resources :instructors
  resources :exams
  resources :courses
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "welcome#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :course
  belongs_to :instructor
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_instructors
	has_many :instructors, through: :course_instructors
	
  validates :title, presence: true
	validates :code, presence: true


end

app/models/course_instructor.rb
class CourseInstructor < ApplicationRecord

  belongs_to :course
  belongs_to :instructor

  has_many :papers

  def course_with_instructor
    "#{Course.find(course_id).title} - #{Instructor.find(instructor_id).name}"
  end

end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :papers
end

app/models/instructor.rb
class Instructor < ApplicationRecord

	has_many :courses, through: :course_instructors
	has_many :course_instructors

end

app/models/paper.rb
class Paper < ApplicationRecord

  belongs_to :program_session, foreign_key: 'program_sessions_id'
  belongs_to :course_instructor, foreign_key: 'course_instructors_id'
  belongs_to :exam

  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/program.rb
class Program < ApplicationRecord

	has_many :sessions, through: :program_sessions

  def name_with_nature
    "#{name} - #{nature}"
  end
end

app/models/program_session.rb
class ProgramSession < ApplicationRecord

  belongs_to :program
  belongs_to :session

  has_many :papers

  def program_with_session
    "#{Program.find(program_id).name_with_nature} - #{Session.find(session_id).session_start_finish}"
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :paper
	has_many :choices, dependent: :destroy
	has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
end

app/models/session.rb
class Session < ApplicationRecord

  has_many :programs, through: :program_sessions

  def session_start_finish
    "#{start.strftime("%Y")} - #{finish.strftime("%Y")}"
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
    3.times do
      question = @paper.questions.build
      3.times { question.choices.build}
    end
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:program_sessions_id, :course_instructors_id, :exam_id, :timeallowed, 
                                    { questions_attributes: [:id, :description, :marks, :_destroy, 
                                     { choices_attributes: [:id, :description, :_destroy] } ] } )
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/papers/_choice_fields.html.erb
<p class="fields">
  <%# <%= f.label :description, "Choice" %1> %> 
  <%= fc.text_area :description, cols: 60, rows:2 %>
  <%= fc.hidden_field :_destroy %>
  <%= link_to_remove_fields "Remove", fc %>
</p>

app/views/papers/_form.html.erb
<%= form_with(model: paper, local: true) do |form| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="same_line">
    <%= form.label :program_sessions_id %>
    <%= form.collection_select :program_sessions_id, ProgramSession.all, :id, :program_with_session %>

  </div>

  <div class="same_line">
    <%= form.label :course_instructors_id %>
    <%= form.collection_select :course_instructors_id, CourseInstructor.all, :id, :course_with_instructor %>
  </div>

  <div class="same_line">
    <%= form.label :exam_id %>
    <%= form.collection_select :exam_id, Exam.all, :id, :title %>
  </div>

  <div class="same_line">
    <%= form.label :timeallowed %>
    <%= form.time_select :timeallowed, default: {hours: '00', minute: '30'} %>
  </div>
  <div>
   <%# <%= link_to_add_fields "Add Question", form, :questions %1> %> 
  </div>

  <div class="field">
    <%= form.fields_for :questions do |builder| %>
      <%= render "question_fields", f: builder %>
   <% end %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/_question_fields.html.erb
<div class="fields" >
  <p>
    <%= f.label :description, "Question" %> 
    <%= f.text_area :description, cols: 60, rows:3 %>
    <%= f.label :marks %>
    <%= f.text_field :marks, value: 1 %>
  </p>
  <b>Choice</b>

  <%= f.fields_for :choices do |builder| %>  
    <%= render 'choice_fields', fc: builder %>
  <% end %>

  <%= link_to_remove_fields "Remove Question", f %>
</div>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Papers</h1>

<table>
  <thead>
    <tr>
      <th>Program sessions</th>
      <th>Course instructors</th>
      <th>Exam</th>
      <th>Timeallowed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.program_session.program.name_with_nature %></td>
        <td><%= paper.course_instructor.course_with_instructor %></td>
        <td><%= paper.exam.title %></td>
        <td><%= paper.timeallowed %></td>
        <td><%= link_to 'Show', paper %></td>
        <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
        <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Program sessions:</strong>
  <%= @paper.program_session.program_with_session %>
</p>

<p>
  <strong>Course instructors:</strong>
  <%= @paper.course_instructor.course_with_instructor %>
</p>

<p>
  <strong>Exam:</strong>
  <%= @paper.exam.title %>
</p>

<p>
  <strong>Timeallowed:</strong>
  <%= @paper.timeallowed %>
</p>
<% @paper.questions.each do |question| %>
<b>Question: </b>
<%=h question.description %>
<b>Marks: </b><%= question.marks %>
<br></br>
<b>Choices: </b>
<ul>
<% question.choices.each do |choice| %>
  <li><%=h choice.description %></li>
<% end %>
<br></br>
</ul>
<% end %>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>